export const defaultRestaurantPalette = {
  primaryColor: "#12355B",
  secondaryColor: "#C7F000",
  backgroundColor: "#FFFFFF",
  surfaceColor: "#FFFFFF",
  textColor: "#1C1C1C",
  mutedColor: "#6B7280",
  borderColor: "#E5E7EB",
  navBackgroundColor: "#12355B",
  navTextColor: "#FFFFFF",
  primaryDark: "#082441",
  primaryLight: "#EAF2F8",
  successColor: "#22C55E",
  dangerColor: "#EF4444",
} as const;

export const restaurantPalettePresets = [
  { name: "Premium claro", colors: defaultRestaurantPalette },
  {
    name: "Midnight operativo",
    colors: {
      primaryColor: "#12355B",
      secondaryColor: "#C7F000",
      backgroundColor: "#F8FAFC",
      surfaceColor: "#FFFFFF",
      textColor: "#1C1C1C",
      mutedColor: "#6B7280",
      borderColor: "#E5E7EB",
      navBackgroundColor: "#12355B",
      navTextColor: "#FFFFFF",
    },
  },
  {
    name: "Nocturno",
    colors: {
      primaryColor: "#C7F000",
      secondaryColor: "#FFFFFF",
      backgroundColor: "#071D33",
      surfaceColor: "#0B2745",
      textColor: "#F8FAFC",
      mutedColor: "#A7B0BE",
      borderColor: "rgba(255,255,255,0.14)",
      navBackgroundColor: "#061A2D",
      navTextColor: "#F8FAFC",
    },
  },
  {
    name: "Claro suave",
    colors: {
      primaryColor: "#12355B",
      secondaryColor: "#C7F000",
      backgroundColor: "#F8FAFC",
      surfaceColor: "#FFFFFF",
      textColor: "#1C1C1C",
      mutedColor: "#6B7280",
      borderColor: "#E5E7EB",
      navBackgroundColor: "#FFFFFF",
      navTextColor: "#12355B",
    },
  },
] as const;
